os: linux
sudo: false
language: go
go:
- '1.10'
install:
- make tools
script:
- make release
deploy:
  skip_cleanup: true
  provider: releases
  prerelease: true
  api_key:
    secure: K6IIRIr6Zx1FvTVht9KQmygrBnZ5/k+18pOg1lziTAm+tCxs/9pWtgUp5VCZJXGM6SwM2oIe1mFld/sb/RARyUCCAz+18Yn6gBI368zasL3ARJ4msJ/9ohVIm7sQ2w8oN8TfOEdjbj1nAaGSQ900pLKPW/nKMeslH6iHII5BTJyd6BejsywFBaYSrMG4ciEL/Qf3OuVM7UavMIgXX++sxwyBgO4R5VJpK/FIRlJNrMvkDcSHye3yWp/14LJbSVTprlYVxYMlXmalWrRMgdN9Ug/drz7dayLsQH6LGF7xkUgR9nQzk8MgUHTOwfPsKeiuoSfaSakFkkkh+SmeFvDjGtKuvs77sWVuxYyPADxlv996YIEZlaTn7Up0G9+Ms28yjrQqOZg1URu5IY25vgKxanCSuRNj8LkQhobixgts90TnnXSNgHzMhk+Rp2tr6KmcizLxEdIZE3GYR8yyUZpzH8QGyOlwXixj8LDpZRp4NMdLH1/zGdPjGLdX9A73IKZhQ38KgkSMz6nHF7MV9BQvj79EM/ZGzEupSkfNSzvO6ag+d5VjYjSXie4jRrA6HKo/G7gdVjFRbQCeMIIY5D3l1KlfNY82l7EkM8W9Ni50o5ZhIK+vwAO6Xwin4+37SOIEa5XU+9VEBvj0IUzWxX+pgL9aEPBGhJmzJ4x2k5CnNfs=
  file:
    - "release/conch-darwin-amd64"
    - "release/conch-linux-amd64"
    - "release/conch-linux-arm"
    - "release/conch-solaris-amd64"
    - "release/conch-freebsd-amd64"
    - "release/conch-openbsd-amd64"
  on:
    tags: true
    repo: joyent/conch-shell
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - sungo@joyent.com
