os: linux
sudo: false
language: go
go:
- '1.10'
install:
- make tools
script:
- make release
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - sungo@joyent.com
